// ==================== CONFIG ====================
export const CONFIG = {
  render: { fov: Math.PI / 3, rayCount: 100, maxDepth: 18, width: 900, height: 560 },
  player: { rotSpeed: 0.003, moveSpeed: 0.0024, radius: 0.2, sprintMult: 1.5 },
  hiding: { drainRate: 0.02, rechargeRate: 0.016, minEnergy: 5 },
  stamina: { drainRate: 0.022, rechargeRate: 0.014 },
  enemy: { chaseRange: 8, minSpawnDist: 5 },
  timing: { invinceDuration: 2500, msgDuration: 2000, trapPenalty: 12000 },
  score: { keyBase: 100, victoryBonus: 500, damagePenalty: 50 },
  items: {
    speedBoostDuration: 10000,
    speedBoostMult: 1.3,
    mapRevealRadius: 5,
  },
  difficulties: {
    EASY: {
      size: 9,
      keys: 2,
      traps: 1,
      heals: 2,
      speeds: 1,
      maps: 1,
      time: 200,
      enemySpeed: 0.0014,
      enemyCount: 1,
      wanderers: 1,
      chasers: 0,
      teleporters: 0,
      lives: 5,
      label: '初級',
      gradient: 'easy',
      sightRange: 5,
      searchDuration: 2500,
      stonePickups: 2,
    },
    NORMAL: {
      size: 11,
      keys: 3,
      traps: 2,
      heals: 1,
      speeds: 1,
      maps: 1,
      time: 170,
      enemySpeed: 0.0018,
      enemyCount: 2,
      wanderers: 1,
      chasers: 1,
      teleporters: 0,
      lives: 3,
      label: '中級',
      gradient: 'normal',
      sightRange: 7,
      searchDuration: 4000,
      stonePickups: 2,
    },
    HARD: {
      size: 14,
      keys: 4,
      traps: 3,
      heals: 1,
      speeds: 1,
      maps: 0,
      time: 140,
      enemySpeed: 0.00216,
      enemyCount: 4,
      wanderers: 1,
      chasers: 2,
      teleporters: 1,
      lives: 2,
      label: '上級',
      gradient: 'hard',
      sightRange: 9,
      searchDuration: 6000,
      stonePickups: 3,
    },
  },
} as const;

// ==================== CONTENT ====================
export const CONTENT = {
  stories: {
    intro: [
      'ここは...どこだ...',
      '気がつくと、暗い迷宮の中にいた。',
      '壁から不気味な呻き声が聞こえる...',
      '「鍵」を見つけて脱出しろ。',
      '迷宮には薬や地図が隠されているらしい。',
      '奴らに捕まるな...生きて帰れ。',
    ],
    victory: [
      '...光だ。',
      '冷たい闇から逃れ、光が差し込む。',
      '脱出成功...だが安心するのはまだ早い。',
      'この迷宮は、次の犠牲者を待っている...',
    ],
    gameover: [
      '冷たい手が首筋に触れた...',
      '足が動かない...声も出ない...',
      '意識が闇に飲まれていく...',
      '【 GAME OVER 】',
    ],
    timeout: [
      '地鳴りが始まった...',
      '天井が崩れ落ちてくる...！',
      '間に合わなかった...迷宮と共に消える...',
      '【 GAME OVER 】',
    ],
  },
  items: {
    key: { emoji: '🔑', name: '鍵', color: '#ffdd00', bgColor: '#4a3800' },
    trap: { emoji: '📦', name: '？箱', color: '#ff8844', bgColor: '#4a2200' },
    heal: { emoji: '💊', name: '回復薬', color: '#44ff88', bgColor: '#004a20' },
    speed: { emoji: '⚡', name: '加速', color: '#ffaa00', bgColor: '#4a3000' },
    map: { emoji: '🗺️', name: '地図', color: '#88ccff', bgColor: '#002a4a' },
    exit: { emoji: '🚪', name: '出口', color: '#44ff88', bgColor: '#003a00' },
    exitLocked: { emoji: '🔒', name: '施錠中', color: '#888888', bgColor: '#333333' },
    enemy: { emoji: '👹', name: '敵', color: '#ff0044', bgColor: '#4a0020' },
    wanderer: { emoji: '👻', name: '亡霊', color: '#aa88ff', bgColor: '#2a0050' },
    teleporter: { emoji: '🌀', name: '歪み', color: '#ff44ff', bgColor: '#4a004a' },
    stone: { emoji: '🪨', name: '小石', color: '#c0b8a8', bgColor: '#3a362f' },
  },
  sounds: {
    footstep: [90, 'triangle', 0.06],
    sprint: [120, 'triangle', 0.05],
    enemy: [42, 'sawtooth', 0.15],
    key: [988, 'sine', 0.3],
    trap: [110, 'square', 0.35],
    door: [660, 'sine', 0.25],
    hurt: [70, 'sawtooth', 0.45],
    heartbeat: [55, 'sine', 0.2],
    heal: [880, 'sine', 0.25],
    speed: [440, 'square', 0.2],
    mapReveal: [550, 'triangle', 0.3],
    teleport: [200, 'sawtooth', 0.3],
    alert: [1150, 'square', 0.25],
    stoneThrow: [320, 'triangle', 0.12],
    stoneLand: [170, 'square', 0.3],
  },
  demo: [
    {
      title: '🎯 ゲームの目的',
      items: ['鍵を全て集める', '出口から脱出する', '制限時間内にクリア'],
      icon: '🏆',
    },
    {
      title: '🔑 アイテム',
      items: ['🔑 鍵：出口を開ける', '💊 回復薬：体力回復', '⚡ 加速：一時的に高速', '🗺️ 地図：周囲公開'],
      icon: '📦',
    },
    {
      title: '👹 敵について',
      items: ['👹 追跡型：プレイヤーを追う', '👻 徘徊型：ランダムに巡回', '🌀 テレポート型：瞬間移動'],
      icon: '⚠️',
    },
    {
      title: '🙈 隠れる',
      items: ['Spaceで隠れる', '見られる前に隠れろ', '動けずゲージ消費'],
      icon: '👁️',
    },
    {
      title: '🪨 小石',
      items: ['クリックで投げる', '音で敵を誘き寄せる', '追跡中の敵には効かない'],
      icon: '🎯',
    },
    {
      title: '🏃 ダッシュ',
      items: ['Shiftで高速移動', '逃げる時に有効', 'スタミナ消費'],
      icon: '💨',
    },
  ],
} as const;
