import { BgmTrack } from '../types/puzzle';

export const bgmTracks: BgmTrack[] = [
  {
    id: 'calm-water',
    name: '静かな水面',
    bpm: 72,
    bars: 8,
    melodyWaveform: 'sine',
    bassWaveform: 'triangle',
    melodyGain: 0.08,
    bassGain: 0.04,
    melody: [
      60, null, 64, null, 67, null, 64, null,
      69, null, 67, null, 64, null, 62, null,
      60, null, 62, null, 64, null, 67, null,
      69, null, 67, null, 64, null, 60, null,
    ],
    bass: [
      48, null, null, null, 52, null, null, null,
      55, null, null, null, 48, null, null, null,
      48, null, null, null, 55, null, null, null,
      52, null, null, null, 48, null, null, null,
    ],
  },
  {
    id: 'starry-waltz',
    name: '星空のワルツ',
    bpm: 84,
    bars: 8,
    melodyWaveform: 'triangle',
    bassWaveform: 'sine',
    melodyGain: 0.07,
    bassGain: 0.03,
    melody: [
      67, null, 71, null, 74, null, 71, null,
      76, null, 74, null, 71, null, 69, null,
      67, null, 69, null, 71, null, 74, null,
      76, null, 74, null, 71, null, 67, null,
    ],
    bass: [
      43, null, null, null, 47, null, null, null,
      50, null, null, null, 43, null, null, null,
      43, null, null, null, 50, null, null, null,
      47, null, null, null, 43, null, null, null,
    ],
  },
  {
    id: 'morning-walk',
    name: '朝の散歩道',
    bpm: 96,
    bars: 8,
    melodyWaveform: 'square',
    bassWaveform: 'sine',
    melodyGain: 0.05,
    bassGain: 0.04,
    melody: [
      65, 67, 69, null, 72, null, 69, 67,
      65, null, 67, 69, 72, 74, 72, null,
      69, 67, 65, null, 67, null, 69, 72,
      74, null, 72, 69, 67, null, 65, null,
    ],
    bass: [
      41, null, null, null, 45, null, null, null,
      48, null, null, null, 41, null, null, null,
      41, null, null, null, 48, null, null, null,
      45, null, null, null, 41, null, null, null,
    ],
  },
  {
    id: 'deep-thought',
    name: '深い思索',
    bpm: 60,
    bars: 8,
    melodyWaveform: 'sine',
    bassWaveform: 'triangle',
    melodyGain: 0.06,
    bassGain: 0.03,
    melody: [
      69, null, null, 72, null, null, 74, null,
      null, 76, null, null, 74, null, 72, null,
      69, null, null, null, 72, null, null, 74,
      null, null, 76, null, null, 74, null, 72,
    ],
    bass: [
      45, null, null, null, null, null, 48, null,
      null, null, null, null, 52, null, null, null,
      45, null, null, null, null, null, 48, null,
      null, null, null, null, 45, null, null, null,
    ],
  },
];
